# package for statistical distributions
using Distributions
# initializing pseudorandom number generation
srand(123)

# hidden coefficient of a linear model: y = mx
m = 3

# explanatory variable X
x = Uniform(0.0, 1000.0)
# there will be some error in measuring it, normally distributed
e = Normal(0.0, 0.1)
# real values for X
x_data = rand(x, 100)
# observed values, affected by noise
x_observed = x_data + rand(e, 100)

# real values for X generated by the latent process
y_data = x_data * m
# observed values, affected by noise
y_observed = y_data + rand(e, 100)

println("x_data:")
println(repr(x_data))
println("y_data:")
println(repr(y_data))

# (ordinary) least squares estimation
pseudoinverse = x_data'*x_data
m = pseudoinverse[1]*x_data'*y_data
println("estimated m:")
println(repr(m))
